# Generated by Django 4.1.4 on 2023-01-18 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data', models.DateField(auto_now_add=True)),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('capa', models.ImageField(blank=True, null=True, upload_to='dados', verbose_name='Capa')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emprestimos.editora')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('data_emp', models.DateField(auto_now_add=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='emprestimo_livro', to='emprestimos.livros')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
