# Generated by Django 4.1.4 on 2022-12-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_alter_autor_options_alter_livros_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
