# Generated by Django 4.1.4 on 2023-01-15 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_alter_livros_autor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
