# Generated by Django 4.1.4 on 2023-01-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_alter_livros_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='altura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livros',
            name='largura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='capa',
            field=models.ImageField(blank=True, height_field='altura', null=True, upload_to='dados', verbose_name='Capa', width_field='largura'),
        ),
    ]
