# Generated by Django 4.1.4 on 2022-12-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0004_alter_livros_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='data',
        ),
        migrations.AddField(
            model_name='livros',
            name='data_pub',
            field=models.DateField(default='2022-12-10', verbose_name='Data de Publicação'),
            preserve_default=False,
        ),
    ]
