# Generated by Django 4.1.4 on 2022-12-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0005_remove_livros_data_livros_data_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='data_pub',
            field=models.DateField(auto_now=True),
        ),
    ]
