# Generated by Django 4.1.4 on 2022-12-10 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0007_alter_livros_data_pub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='data_pub',
            new_name='data',
        ),
    ]
