# Generated by Django 4.1.4 on 2022-12-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0008_rename_data_pub_livros_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='quantidade',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade'),
            preserve_default=False,
        ),
    ]
