# Generated by Django 4.1.4 on 2022-12-10 20:01

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0009_livros_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emprestimos.autor'),
        ),
        migrations.AlterField(
            model_name='livros',
            name='editora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emprestimos.editora'),
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('codigo', models.BigIntegerField(primary_key=builtins.id, serialize=False)),
                ('usuario', models.CharField(max_length=50, verbose_name='Usuario')),
                ('data_emp', models.DateField(verbose_name='Data de Emprestimo')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emprestimos.livros')),
            ],
        ),
    ]
