# Generated by Django 4.1.4 on 2022-12-10 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0012_emprestimo_id_alter_emprestimo_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Emprestimo', to='emprestimos.livros'),
        ),
    ]
