# Generated by Django 4.1.4 on 2022-12-10 20:19

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0013_alter_emprestimo_livro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='id',
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='codigo',
            field=models.BigIntegerField(primary_key=builtins.id, serialize=False),
        ),
    ]
