# Generated by Django 4.1.4 on 2022-12-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0014_remove_emprestimo_id_alter_emprestimo_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='codigo',
            field=models.BigIntegerField(auto_created=True),
        ),
    ]
